"""Explicit wave-056 recipe catalog for science, engineering, CS, and biology."""
from __future__ import annotations

from collections import Counter
from typing import Any

from .model import DomainRecipe, RecipeBinding

# context, first quantity, second quantity, result, operation, principle, unit
BLUEPRINTS: dict[str, tuple[tuple[str, ...], ...]] = {
"MECHANICS": (("A cart receives two collinear rightward impulses.","first impulse","second impulse","net impulse","add","linear impulse-momentum conservation","N*s"),("A projectile's horizontal displacement is compared at two observation times.","later displacement","earlier displacement","displacement interval","subtract","kinematic displacement definition","m"),("A constant force acts through a measured displacement.","force magnitude","displacement","work","multiply","work-energy theorem","J"),("A rigid body has two orthogonal angular-velocity components.","x angular component","y angular component","component trace","add","rigid-body angular kinematics","rad/s"),("Two masses move together after a perfectly inelastic collision.","first momentum","second momentum","total momentum","add","linear momentum conservation","kg*m/s")),
"WAVES_AND_OPTICS": (("Two phase-aligned pulses meet on a string.","first amplitude","second amplitude","superposed amplitude","add","linear superposition","mm"),("A wave train passes a detector for a measured duration.","cycle count","elapsed time","frequency","ratio","frequency definition","Hz"),("A converging lens forms a real image with positive measured distances.","object distance contribution","image distance contribution","conjugate-distance check","add","thin-lens conjugate relation","cm"),("Two coherent paths arrive with measured path lengths.","longer path","shorter path","path difference","subtract","interference path criterion","nm"),("A standing wave spans equal half-wavelength segments.","half-wavelength","segment count","string length","multiply","standing-wave boundary condition","m")),
"MODERN_PHYSICS": (("A photon packet contains equal-energy photons.","photon energy","photon count","packet energy","multiply","photon energy quantization","eV"),("An atomic electron drops between two stated levels.","initial energy","final energy","emitted energy","subtract","atomic energy conservation","eV"),("A radioactive sample is counted before and after an interval.","initial nuclei","remaining nuclei","decayed nuclei","subtract","radioactive population accounting","nuclei"),("A particle's relativistic energy has two reported contributions.","rest-energy contribution","kinetic-energy contribution","total energy","add","relativistic energy accounting","MeV"),("A matter wave traverses repeated equal wavelengths.","wavelength","cycle count","path length","multiply","de Broglie wave periodicity","nm")),
"DYNAMICS": (("Two collinear forces accelerate a particle in the declared positive direction.","first applied force","second applied force","resultant force","add","Newton's second law balance","N"),("A particle changes its speed over a measured interval.","final speed","initial speed","speed change","subtract","particle kinematics","m/s"),("A rigid disk receives two same-sense torques.","drive torque","load torque contribution","resultant torque","add","angular impulse-momentum balance","N*m"),("A force acts through a displacement along its line of action.","force","displacement","work input","multiply","work-energy balance","J"),("A vibration record contains equal periods.","period","cycle count","record duration","multiply","periodic motion definition","s")),
"MECHANICS_OF_MATERIALS": (("An axially loaded prismatic bar carries two same-direction loads.","service load","added load","total axial load","add","axial-force equilibrium","kN"),("A uniform axial load is distributed over a section.","axial force","cross-sectional area","normal stress","ratio","uniaxial stress relation","MPa"),("A beam section receives bending contributions of the same sign.","dead-load moment","live-load moment","total bending moment","add","elastic load superposition","kN*m"),("A circular shaft transmits torque through a stated twist measure.","torque measure","twist measure","torsional response index","multiply","Saint-Venant torsion relation","N*m"),("A column's demand is compared with its critical load.","critical load","applied load","remaining stability margin","subtract","Euler stability criterion","kN")),
"STRENGTH_OF_MATERIALS": (("A point has two same-sign normal-stress contributions.","primary stress","secondary stress","combined stress","add","stress superposition","MPa"),("A thin pressure vessel has a measured pressure-area resultant.","pressure measure","area measure","force resultant","multiply","pressure-vessel equilibrium","kN"),("A fatigue coupon completes repeated blocks of cycles.","cycles per block","block count","accumulated cycles","multiply","fatigue cycle accounting","cycles"),("A design resistance is compared with an applied demand.","material resistance","applied demand","strength margin","subtract","limit-state strength check","MPa"),("A column carries two concentric compressive loads.","permanent load","variable load","total column load","add","column-force equilibrium","kN")),
"FLUID_MECHANICS": (("Two incompressible inlet streams enter one control volume.","primary inflow","secondary inflow","total inflow","add","control-volume continuity","m^3/s"),("A static liquid column spans two elevations.","upper elevation","lower elevation","column height","subtract","hydrostatic pressure relation","m"),("A uniform stream crosses a rectangular area.","mean velocity","flow area","volume flow rate","multiply","kinematic flow-rate definition","m^3/s"),("A viscous pipe has two consecutive head losses.","first-section loss","second-section loss","total head loss","add","mechanical-energy loss accounting","m"),("A body experiences pressure and skin-friction drag in one direction.","pressure drag","friction drag","total drag","add","external-flow force balance","N")),
"HYDRAULICS": (("A tributary joins a main channel at a junction.","main discharge","tributary discharge","downstream discharge","add","junction continuity","m^3/s"),("A pipe run contains two consecutive minor-loss sections.","first head loss","second head loss","total head loss","add","hydraulic energy accounting","m"),("A pump adds head above an upstream datum.","upstream head","pump head","delivered head","add","pump energy equation","m"),("An open channel has uniform depth across a rectangular width.","flow depth","channel width","flow area","multiply","open-channel geometry","m^2"),("A reservoir level exceeds an outlet elevation.","reservoir elevation","outlet elevation","available static head","subtract","hydraulic grade definition","m")),
"FLUID_DYNAMICS": (("Two velocity contributions align in the streamwise direction.","base velocity","perturbation velocity","instantaneous velocity","add","velocity-field superposition","m/s"),("A planar field enters and leaves a differential control region.","outward flux","inward flux","net flux","subtract","differential continuity","m^3/s"),("A shear layer changes velocity across a measured gap.","upper velocity","lower velocity","velocity difference","subtract","boundary-layer shear kinematics","m/s"),("Two same-sense circulation contributions enclose a contour.","first circulation","second circulation","total circulation","add","circulation-vorticity relation","m^2/s"),("A compressible stream transports density through an area.","mass flux","flow area","mass flow rate","multiply","compressible mass conservation","kg/s")),
"DATA_STRUCTURES": (("A stack receives a bounded batch of pushes after initialization.","initial size","push count","final stack size","add","stack LIFO size invariant","items"),("A linked list removes nodes from a known population.","initial node count","removed node count","remaining nodes","subtract","linked-list reachability invariant","nodes"),("A hash table divides occupied slots by total slots.","occupied slots","total slots","load factor","ratio","hash-table load-factor definition","ratio"),("A graph combines disjoint adjacency lists for one vertex.","first neighbor count","second neighbor count","degree","add","adjacency degree invariant","edges"),("A binary tree level has fixed-width groups repeated across subtrees.","nodes per subtree","subtree count","level population","multiply","tree structural invariant","nodes")),
"ALGORITHMS": (("A divide-and-conquer trace combines two disjoint operation blocks.","left operations","right operations","combined operations","add","operation-count composition","operations"),("Binary search eliminates candidates from a known interval.","initial candidates","eliminated candidates","remaining candidates","subtract","binary-search interval invariant","items"),("A dynamic program fills equal numbers of states in repeated rows.","states per row","row count","table states","multiply","dynamic-program state decomposition","states"),("A graph traversal processes two disconnected components.","first component visits","second component visits","total visits","add","graph traversal visitation invariant","vertices"),("A sorting pass compares adjacent pairs across repeated passes.","comparisons per pass","pass count","total comparisons","multiply","comparison-sort cost model","comparisons")),
"COMPUTATIONAL_THINKING": (("A decomposition splits a task into two disjoint sets of subtasks.","first subtask count","second subtask count","total subtasks","add","problem decomposition","tasks"),("A pattern classifier compares matched cases with all cases.","matched cases","observed cases","match rate","percent","pattern-recognition rate","percent"),("A simulation repeats an equal number of steps for each trial.","steps per trial","trial count","executed steps","multiply","bounded simulation design","steps"),("A debugging trace removes confirmed-correct statements from all statements.","all traced statements","confirmed statements","suspect statements","subtract","fault-isolation procedure","statements"),("An abstraction combines two nonoverlapping state groups.","first abstract states","second abstract states","model states","add","state-space abstraction","states")),
"BIOLOGY": (("Replicate cultures yield two independently counted cell groups.","first culture cells","second culture cells","observed cells","add","controlled biological replication","cells"),("A cell's ATP ledger records production and consumption.","ATP produced","ATP consumed","net ATP","subtract","cellular energy conservation","ATP molecules"),("A genetic cross counts offspring with a phenotype among all offspring.","phenotype count","offspring count","phenotype frequency","percent","Mendelian phenotype frequency","percent"),("An ecosystem survey combines individuals from two nonoverlapping quadrats.","first quadrat count","second quadrat count","sample abundance","add","ecological sampling additivity","organisms"),("A population experiences equal additions across repeated generations.","addition per generation","generation count","population addition","multiply","population accounting","organisms")),
"ORGANIC_CHEMISTRY": (("Two resonance contributors assign electron counts to the same bounded atom set.","first electron contribution","second contribution","accounted electrons","add","valence-electron conservation","electrons"),("A proton-transfer experiment compares initial and remaining acid equivalents.","initial acid equivalents","remaining equivalents","transferred equivalents","subtract","Brønsted acid-base stoichiometry","mmol"),("A reaction vessel combines two portions of the same substrate.","first substrate amount","second substrate amount","total substrate","add","organic reaction mass accounting","mmol"),("A stereochemical sample counts one enantiomer among all molecules sampled.","selected enantiomer count","sample count","enantiomer percentage","percent","stereochemical composition","percent"),("Two spectroscopy integrations belong to nonoverlapping proton environments.","first integration","second integration","total integrated protons","add","NMR integration accounting","protons")),
"BIOCHEMISTRY": (("A pathway produces ATP in two substrate-level steps.","first-step ATP","second-step ATP","pathway ATP","add","metabolic energy accounting","mmol ATP"),("A buffer preparation combines conjugate-base portions.","first base amount","second base amount","total conjugate base","add","buffer component conservation","mmol"),("An enzyme assay divides converted substrate by elapsed time.","substrate converted","elapsed time","initial rate","ratio","enzyme rate definition","umol/min"),("A membrane experiment counts transported molecules among presented molecules.","transported molecules","presented molecules","transport percentage","percent","selective membrane transport","percent"),("A protein contains repeated residues in equal subunits.","residues per subunit","subunit count","protein residues","multiply","protein subunit stoichiometry","residues")),
}

# These bindings are deliberately ordered to match topic/skill/family identities
# 001..005 (001,002,003,004,007 for the two chemistry catalogs).  Keeping this
# semantic manifest separate makes an identity-preserving but topic-shifted edit
# visible to audit rather than allowing an ID-only test to pass.
SEMANTIC_BLUEPRINTS = {
"MECHANICS": (("A vector measurement is resolved from two collinear positive components.","first component","second component","measured magnitude","add","vector component composition","m"),("A particle's displacement is recorded at two times.","final position","initial position","displacement","subtract","kinematic displacement definition","m"),("Two collinear forces act in the declared positive direction.","first force","second force","net force","add","Newtonian force balance","N"),("A constant force acts through a displacement.","force","displacement","work","multiply","work-energy theorem","J"),("Two bodies contribute momentum before a collision.","first momentum","second momentum","system momentum","add","linear momentum conservation","kg*m/s")),
"WAVES_AND_OPTICS": (("A periodic wave passes a detector for a measured duration.","cycle count","elapsed time","frequency","ratio","wave frequency definition","Hz"),("Two phase-aligned pulses meet on a string.","first amplitude","second amplitude","superposed amplitude","add","linear superposition","mm"),("A sound detector counts pressure cycles during an interval.","sound cycles","elapsed time","sound frequency","ratio","acoustic frequency definition","Hz"),("A thin lens has positive object and image distance contributions.","object vergence index","image vergence index","optical conjugate index","add","thin-lens conjugate relation","1/m"),("Two coherent optical paths arrive at a screen.","longer path","shorter path","path difference","subtract","interference path criterion","nm")),
"MODERN_PHYSICS": (("A relativistic particle's total energy includes rest and kinetic contributions.","rest energy","kinetic energy","total relativistic energy","add","relativistic energy accounting","MeV"),("A packet contains equal-energy photons.","photon energy","photon count","packet energy","multiply","photon energy quantization","eV"),("A matter wave repeats across equal wavelengths.","de Broglie wavelength","cycle count","matter-wave path","multiply","de Broglie periodicity","nm"),("Two permitted quantum contributions form a bounded model energy.","base-state energy","excitation contribution","modeled quantum energy","add","quantum state energy accounting","eV"),("An atomic electron drops between stated levels.","initial level energy","final level energy","emitted energy","subtract","atomic transition conservation","eV")),
"DYNAMICS": (("A particle's positions are compared in a kinematic trace.","final position","initial position","displacement","subtract","particle kinematics","m"),("Two collinear forces act on a particle.","first applied force","second applied force","resultant force","add","particle kinetic force balance","N"),("A force acts along a particle displacement.","force","displacement","work input","multiply","work-energy balance","J"),("Two same-direction impulses act during an event.","first impulse","second impulse","total impulse","add","impulse-momentum balance","N*s"),("Two same-sense torques act on a planar rigid body.","drive torque","applied torque","resultant torque","add","planar rigid-body moment balance","N*m")),
"MECHANICS_OF_MATERIALS": (("A material point receives two same-sign normal stresses.","first stress","second stress","combined stress","add","stress-strain accounting","MPa"),("A linear-elastic specimen's response combines two strain increments.","first strain increment","second strain increment","total strain","add","linear material behavior","microstrain"),("An axial member carries two same-direction loads.","service load","added load","axial load","add","axial-force equilibrium","kN"),("A shaft carries two same-sense torques.","first torque","second torque","transmitted torque","add","Saint-Venant torsion equilibrium","N*m"),("A beam receives two same-sign bending moments.","dead-load moment","live-load moment","bending moment","add","beam bending superposition","kN*m")),
"STRENGTH_OF_MATERIALS": (("Two connected members transmit collinear loads along a load path.","first member load","second member load","path load","add","load-path equilibrium","kN"),("Two same-sign transformed normal-stress components act on a plane.","first transformed stress","second transformed stress","plane stress","add","stress transformation","MPa"),("A failure criterion compares material resistance with applied demand.","material resistance","applied demand","failure margin","subtract","limit-state failure criterion","MPa"),("A thin pressure vessel combines two membrane-force contributions.","longitudinal contribution","hoop contribution","membrane demand","add","pressure-vessel equilibrium","kN/m"),("A column carries permanent and variable compression.","permanent load","variable load","column load","add","column stability loading","kN")),
"FLUID_MECHANICS": (("Two measured density contributions characterize a bounded mixture.","base density","density increment","mixture density","add","fluid property accounting","kg/m^3"),("A static liquid spans two elevations.","upper elevation","lower elevation","column height","subtract","hydrostatic pressure relation","m"),("Two inlet streams enter one control volume.","primary inflow","secondary inflow","total inflow","add","control-volume continuity","m^3/s"),("A uniform stream crosses a rectangular area.","mean velocity","flow area","volume flow rate","multiply","fluid kinematic flow-rate definition","m^3/s"),("Two inlet momentum-flux contributions enter a control volume.","first momentum flux","second momentum flux","total momentum flux","add","control-volume momentum balance","N")),
"HYDRAULICS": (("A manometer compares two pressure-head elevations.","higher head","lower head","measured pressure head","subtract","hydrostatic pressure measurement","m"),("Two pipe sections carry discharge into a junction.","first pipe discharge","second pipe discharge","combined pipe discharge","add","pipe-flow continuity","m^3/s"),("A pipe system has consecutive local losses.","first minor loss","second minor loss","total minor loss","add","minor-loss energy accounting","m"),("A pump adds head above an upstream datum.","upstream head","pump head","delivered head","add","pump energy equation","m"),("A rectangular open channel has a measured depth and width.","flow depth","channel width","flow area","multiply","open-channel geometry","m^2")),
"FLUID_DYNAMICS": (("Two aligned components describe an Eulerian velocity field.","base velocity","perturbation velocity","field velocity","add","Eulerian field description","m/s"),("A differential control region has outward and inward flux.","outward flux","inward flux","net flux","subtract","differential continuity","m^3/s"),("Two pressure-gradient contributions act in an inviscid stream.","first pressure-gradient term","second pressure-gradient term","Euler acceleration term","add","Euler momentum equation","m/s^2"),("Viscous and pressure terms contribute to a modeled flow balance.","viscous term","pressure term","Navier-Stokes balance term","add","Navier-Stokes momentum model","m/s^2"),("Two same-sense circulation contributions enclose a contour.","first circulation","second circulation","total circulation","add","circulation-vorticity relation","m^2/s")),
"DATA_STRUCTURES": (("An abstract collection combines two disjoint item groups.","first ADT size","second ADT size","abstract collection size","add","abstract-data-type size invariant","items"),("A linked list removes nodes from a known population.","initial node count","removed node count","remaining nodes","subtract","linked-list reachability invariant","nodes"),("A stack receives a bounded batch of pushes.","initial stack size","push count","final stack size","add","stack LIFO size invariant","items"),("A hash table divides occupied slots by total slots.","occupied slots","total slots","load factor","ratio","hash-table load-factor invariant","ratio"),("Equal-size subtrees form a bounded tree level.","nodes per subtree","subtree count","level population","multiply","tree structural invariant","nodes")),
"ALGORITHMS": (("Two disjoint algorithm phases contribute operation counts.","first-phase operations","second-phase operations","total operations","add","algorithm cost composition","operations"),("Binary search removes candidates from an interval.","initial candidates","eliminated candidates","remaining candidates","subtract","binary-search interval invariant","items"),("A sorting algorithm repeats equal comparison passes.","comparisons per pass","pass count","total comparisons","multiply","comparison-sort cost model","comparisons"),("A divide-and-conquer call combines two recursive costs.","left subproblem cost","right subproblem cost","combined recursive cost","add","divide-and-conquer recurrence","operations"),("A greedy selection combines accepted weights from two steps.","first accepted weight","second accepted weight","greedy partial weight","add","greedy-choice accumulation","weight units")),
"COMPUTATIONAL_THINKING": (("A decomposition splits a task into disjoint subtask sets.","first subtask count","second subtask count","total subtasks","add","problem decomposition","tasks"),("A classifier compares matched cases with observed cases.","matched cases","observed cases","pattern match rate","percent","pattern recognition","percent"),("An abstraction combines two nonoverlapping state groups.","first abstract states","second abstract states","model states","add","state-space abstraction","states"),("An algorithm repeats equal steps across input groups.","steps per group","group count","algorithm steps","multiply","bounded algorithm design","steps"),("A representation allocates equal bits to repeated records.","bits per record","record count","represented bits","multiply","data representation","bits")),
"BIOLOGY": (("Two replicate cultures yield independently counted observations.","first replicate count","second replicate count","observed cells","add","controlled scientific inquiry","cells"),("Two nonoverlapping molecular pools contribute to a cell sample.","first molecular count","second molecular count","chemical inventory","add","chemistry-of-life conservation","molecules"),("Two organelle populations are counted in a cell section.","first organelle count","second organelle count","cell organelles","add","cell structural organization","organelles"),("A cell's ATP ledger records production and consumption.","ATP produced","ATP consumed","net cellular energy","subtract","cellular energetic conservation","ATP molecules"),("Equal chromosome sets segregate into daughter cells.","chromosomes per daughter","daughter cell count","segregated chromosomes","multiply","cell-division chromosome accounting","chromosomes")),
"ORGANIC_CHEMISTRY": (("Two bonds contribute electrons to a bounded Lewis structure.","first bond electrons","second bond electrons","accounted valence electrons","add","organic structure and bonding","electrons"),("Two nonoverlapping functional-group counts occur in a molecule set.","first group count","second group count","functional groups","add","functional-group classification","groups"),("A proton-transfer experiment compares initial and remaining acid equivalents.","initial acid equivalents","remaining equivalents","transferred equivalents","subtract","Brønsted acid-base stoichiometry","mmol"),("A sample counts one enantiomer among all stereoisomers observed.","selected enantiomer count","sample count","enantiomer percentage","percent","stereochemical composition","percent"),("Two alkene portions consume equal hydrogen equivalents per mole.","first alkene amount","second alkene amount","hydrogenation demand","add","alkene addition stoichiometry","mmol")),
"BIOCHEMISTRY": (("A buffer combines two portions of conjugate base.","first base amount","second base amount","total conjugate base","add","buffer component conservation","mmol"),("Two peptide segments contribute amino-acid residues.","first segment residues","second segment residues","peptide residues","add","amino-acid residue accounting","residues"),("Equal protein subunits assemble into an oligomer.","residues per subunit","subunit count","protein residues","multiply","protein structural stoichiometry","residues"),("An enzyme assay divides converted substrate by elapsed time.","substrate converted","elapsed time","initial enzyme rate","ratio","enzyme kinetic rate definition","umol/min"),("Two nucleic-acid strands contribute nucleotide counts.","first strand nucleotides","second strand nucleotides","total nucleotides","add","nucleic-acid composition","nucleotides")),
}
BLUEPRINTS.update(SEMANTIC_BLUEPRINTS)

SEMANTIC_REQUIREMENTS = {
"MECHANICS": (("vector","measurement"),("kinematic","displacement"),("newton","force"),("work","energy"),("momentum",)),
"WAVES_AND_OPTICS": (("wave","frequency"),("superposition",),("sound","acoustic"),("lens","optical"),("interference","path")),
"MODERN_PHYSICS": (("relativistic",),("photon",),("matter wave","de broglie"),("quantum",),("atomic","transition")),
"DYNAMICS": (("kinematic",),("kinetic","force"),("work","energy"),("impulse","momentum"),("rigid body","torque")),
"MECHANICS_OF_MATERIALS": (("stress","strain"),("material",),("axial",),("torsion","shaft"),("beam","bending")),
"STRENGTH_OF_MATERIALS": (("load path",),("stress transformation","transformed"),("failure","limit-state"),("pressure vessel",),("column",)),
"FLUID_MECHANICS": (("fluid property","density"),("hydrostatic",),("control volume",),("kinematic",),("momentum",)),
"HYDRAULICS": (("pressure","manometer"),("pipe",),("minor loss","minor-loss"),("pump",),("open channel",)),
"FLUID_DYNAMICS": (("field","eulerian"),("continuity",),("euler",),("navier-stokes",),("vorticity","circulation")),
"DATA_STRUCTURES": (("abstract",),("linked list",),("stack",),("hash",),("tree",)),
"ALGORITHMS": (("algorithm cost","operation"),("search",),("sort",),("divide-and-conquer",),("greedy",)),
"COMPUTATIONAL_THINKING": (("decomposition",),("pattern",),("abstraction",),("algorithm",),("representation",)),
"BIOLOGY": (("scientific inquiry",),("chemistry-of-life","molecular"),("cell structural","organelle"),("cellular energetic","atp"),("cell-division","chromosome")),
"ORGANIC_CHEMISTRY": (("structure and bonding","lewis"),("functional-group",),("acid-base","proton"),("stereochemical","enantiomer"),("alkene",)),
"BIOCHEMISTRY": (("buffer",),("amino-acid",),("protein structural",),("enzyme kinetic",),("nucleic-acid","nucleotide")),
}

COURSE_IDS = tuple(BLUEPRINTS)
_PHYSICS_ENGINES = ("numeric_scalar","numeric_scalar","numeric_scalar","numeric_vector","numeric_scalar")
_CS_ENGINES = ("code_execution_python","multiple_choice","numeric_vector","rubric_scored_explanation","code_execution_python")
_LIFE_ENGINES = ("scientific_structured_response","rubric_scored_explanation","numeric_scalar","multiple_choice","scientific_structured_response")


def _build() -> tuple[DomainRecipe, ...]:
    rows=[]
    for course, specs in BLUEPRINTS.items():
        engines = _CS_ENGINES if course in {"DATA_STRUCTURES","ALGORITHMS","COMPUTATIONAL_THINKING"} else (_LIFE_ENGINES if course in {"BIOLOGY","ORGANIC_CHEMISTRY","BIOCHEMISTRY"} else _PHYSICS_ENGINES)
        indexes = (1,2,3,4,7) if course in {"ORGANIC_CHEMISTRY","BIOCHEMISTRY"} else (1,2,3,4,5)
        for spec, engine, index in zip(specs, engines, indexes):
            context, first, second, result, operation, principle, unit = spec
            binding=RecipeBinding(course,f"{course}_TOPIC_{index:03d}",f"{course}_SKILL_{index:03d}",f"{course}_PROC_{index:03d}",f"{course}_FAMILY_{index:03d}",engine)
            rows.append(DomainRecipe(f"W056:{course}:{index:03d}","1.0.0",binding,(first,second,result),operation,principle,context,unit))
    return tuple(rows)


RECIPES = _build()


def recipes_for_course(course_id: str) -> tuple[DomainRecipe, ...]:
    if course_id not in COURSE_IDS: raise KeyError(f"no exact recipe binding for {course_id}")
    return tuple(r for r in RECIPES if r.binding.course_id == course_id)


def semantic_compatibility_manifest() -> tuple[dict[str, Any], ...]:
    manifest=[]
    for course in COURSE_IDS:
        for recipe, alternatives in zip(recipes_for_course(course), SEMANTIC_REQUIREMENTS[course]):
            material=f"{recipe.context} {recipe.principle}".lower()
            manifest.append({"recipe_id":recipe.recipe_id,"binding":recipe.binding.__dict__,"accepted_domain_terms":list(alternatives),"matched_terms":[term for term in alternatives if term in material],"status":"PASS" if any(term in material for term in alternatives) else "FAIL"})
    return tuple(manifest)


def self_audit() -> dict[str, Any]:
    rows=[]; prompts=[]
    for course in COURSE_IDS:
        recipes=recipes_for_course(course); compiled=[r.compile(v) for r in recipes for v in range(5)]
        prompts.extend(x.prompt for x in compiled)
        semantic_matches=[]
        for recipe, alternatives in zip(recipes, SEMANTIC_REQUIREMENTS[course]):
            material=f"{recipe.context} {recipe.principle}".lower()
            semantic_matches.append(any(term in material for term in alternatives))
        rows.append({"course_id":course,"recipes":len(recipes),"questions":len(compiled),"families":len({r.binding.family_id for r in recipes}),"skills":len({r.binding.micro_skill_id for r in recipes}),"procedures":len({r.binding.procedure_id for r in recipes}),"engines":len({r.binding.engine_type for r in recipes}),"difficulties":len({x.difficulty for x in compiled}),"independent_derivations":sum(x.generated_answer==x.independently_derived_answer for x in compiled),"semantic_compatibility":sum(semantic_matches)})
    duplicate_count=sum(n-1 for n in Counter(prompts).values() if n>1)
    valid=all(r["recipes"]>=5 and r["questions"]==25 and r["families"]>=5 and r["skills"]>=5 and r["procedures"]>=3 and r["engines"]>=2 and r["difficulties"]>=2 and r["independent_derivations"]==25 and r["semantic_compatibility"]==5 for r in rows)
    manifest=semantic_compatibility_manifest()
    return {"status":"PASS" if valid and not duplicate_count and all(x["status"]=="PASS" for x in manifest) else "FAIL","course_count":len(rows),"recipe_count":len(RECIPES),"question_count":sum(r["questions"] for r in rows),"independent_derivations":sum(r["independent_derivations"] for r in rows),"exact_prompt_duplicates":duplicate_count,"semantic_compatibility_manifest":manifest,"rows":rows}
