"""Explicit wave-056 recipe catalog for science, engineering, CS, and biology."""
from __future__ import annotations

from collections import Counter
from typing import Any

from .model import DomainRecipe, RecipeBinding

# context, first quantity, second quantity, result, operation, principle, unit
BLUEPRINTS: dict[str, tuple[tuple[str, ...], ...]] = {
"MECHANICS": (("A cart receives two collinear rightward impulses.","first impulse","second impulse","net impulse","add","linear impulse-momentum conservation","N*s"),("A projectile's horizontal displacement is compared at two observation times.","later displacement","earlier displacement","displacement interval","subtract","kinematic displacement definition","m"),("A constant force acts through a measured displacement.","force magnitude","displacement","work","multiply","work-energy theorem","J"),("A rigid body has two orthogonal angular-velocity components.","x angular component","y angular component","component trace","add","rigid-body angular kinematics","rad/s"),("Two masses move together after a perfectly inelastic collision.","first momentum","second momentum","total momentum","add","linear momentum conservation","kg*m/s")),
"WAVES_AND_OPTICS": (("Two phase-aligned pulses meet on a string.","first amplitude","second amplitude","superposed amplitude","add","linear superposition","mm"),("A wave train passes a detector for a measured duration.","cycle count","elapsed time","frequency","ratio","frequency definition","Hz"),("A converging lens forms a real image with positive measured distances.","object distance contribution","image distance contribution","conjugate-distance check","add","thin-lens conjugate relation","cm"),("Two coherent paths arrive with measured path lengths.","longer path","shorter path","path difference","subtract","interference path criterion","nm"),("A standing wave spans equal half-wavelength segments.","half-wavelength","segment count","string length","multiply","standing-wave boundary condition","m")),
"MODERN_PHYSICS": (("A photon packet contains equal-energy photons.","photon energy","photon count","packet energy","multiply","photon energy quantization","eV"),("An atomic electron drops between two stated levels.","initial energy","final energy","emitted energy","subtract","atomic energy conservation","eV"),("A radioactive sample is counted before and after an interval.","initial nuclei","remaining nuclei","decayed nuclei","subtract","radioactive population accounting","nuclei"),("A particle's relativistic energy has two reported contributions.","rest-energy contribution","kinetic-energy contribution","total energy","add","relativistic energy accounting","MeV"),("A matter wave traverses repeated equal wavelengths.","wavelength","cycle count","path length","multiply","de Broglie wave periodicity","nm")),
"DYNAMICS": (("Two collinear forces accelerate a particle in the declared positive direction.","first applied force","second applied force","resultant force","add","Newton's second law balance","N"),("A particle changes its speed over a measured interval.","final speed","initial speed","speed change","subtract","particle kinematics","m/s"),("A rigid disk receives two same-sense torques.","drive torque","load torque contribution","resultant torque","add","angular impulse-momentum balance","N*m"),("A force acts through a displacement along its line of action.","force","displacement","work input","multiply","work-energy balance","J"),("A vibration record contains equal periods.","period","cycle count","record duration","multiply","periodic motion definition","s")),
"MECHANICS_OF_MATERIALS": (("An axially loaded prismatic bar carries two same-direction loads.","service load","added load","total axial load","add","axial-force equilibrium","kN"),("A uniform axial load is distributed over a section.","axial force","cross-sectional area","normal stress","ratio","uniaxial stress relation","MPa"),("A beam section receives bending contributions of the same sign.","dead-load moment","live-load moment","total bending moment","add","elastic load superposition","kN*m"),("A circular shaft transmits torque through a stated twist measure.","torque measure","twist measure","torsional response index","multiply","Saint-Venant torsion relation","N*m"),("A column's demand is compared with its critical load.","critical load","applied load","remaining stability margin","subtract","Euler stability criterion","kN")),
"STRENGTH_OF_MATERIALS": (("A point has two same-sign normal-stress contributions.","primary stress","secondary stress","combined stress","add","stress superposition","MPa"),("A thin pressure vessel has a measured pressure-area resultant.","pressure measure","area measure","force resultant","multiply","pressure-vessel equilibrium","kN"),("A fatigue coupon completes repeated blocks of cycles.","cycles per block","block count","accumulated cycles","multiply","fatigue cycle accounting","cycles"),("A design resistance is compared with an applied demand.","material resistance","applied demand","strength margin","subtract","limit-state strength check","MPa"),("A column carries two concentric compressive loads.","permanent load","variable load","total column load","add","column-force equilibrium","kN")),
"FLUID_MECHANICS": (("Two incompressible inlet streams enter one control volume.","primary inflow","secondary inflow","total inflow","add","control-volume continuity","m^3/s"),("A static liquid column spans two elevations.","upper elevation","lower elevation","column height","subtract","hydrostatic pressure relation","m"),("A uniform stream crosses a rectangular area.","mean velocity","flow area","volume flow rate","multiply","kinematic flow-rate definition","m^3/s"),("A viscous pipe has two consecutive head losses.","first-section loss","second-section loss","total head loss","add","mechanical-energy loss accounting","m"),("A body experiences pressure and skin-friction drag in one direction.","pressure drag","friction drag","total drag","add","external-flow force balance","N")),
"HYDRAULICS": (("A tributary joins a main channel at a junction.","main discharge","tributary discharge","downstream discharge","add","junction continuity","m^3/s"),("A pipe run contains two consecutive minor-loss sections.","first head loss","second head loss","total head loss","add","hydraulic energy accounting","m"),("A pump adds head above an upstream datum.","upstream head","pump head","delivered head","add","pump energy equation","m"),("An open channel has uniform depth across a rectangular width.","flow depth","channel width","flow area","multiply","open-channel geometry","m^2"),("A reservoir level exceeds an outlet elevation.","reservoir elevation","outlet elevation","available static head","subtract","hydraulic grade definition","m")),
"FLUID_DYNAMICS": (("Two velocity contributions align in the streamwise direction.","base velocity","perturbation velocity","instantaneous velocity","add","velocity-field superposition","m/s"),("A planar field enters and leaves a differential control region.","outward flux","inward flux","net flux","subtract","differential continuity","m^3/s"),("A shear layer changes velocity across a measured gap.","upper velocity","lower velocity","velocity difference","subtract","boundary-layer shear kinematics","m/s"),("Two same-sense circulation contributions enclose a contour.","first circulation","second circulation","total circulation","add","circulation-vorticity relation","m^2/s"),("A compressible stream transports density through an area.","mass flux","flow area","mass flow rate","multiply","compressible mass conservation","kg/s")),
"DATA_STRUCTURES": (("A stack receives a bounded batch of pushes after initialization.","initial size","push count","final stack size","add","stack LIFO size invariant","items"),("A linked list removes nodes from a known population.","initial node count","removed node count","remaining nodes","subtract","linked-list reachability invariant","nodes"),("A hash table divides occupied slots by total slots.","occupied slots","total slots","load factor","ratio","hash-table load-factor definition","ratio"),("A graph combines disjoint adjacency lists for one vertex.","first neighbor count","second neighbor count","degree","add","adjacency degree invariant","edges"),("A binary tree level has fixed-width groups repeated across subtrees.","nodes per subtree","subtree count","level population","multiply","tree structural invariant","nodes")),
"ALGORITHMS": (("A divide-and-conquer trace combines two disjoint operation blocks.","left operations","right operations","combined operations","add","operation-count composition","operations"),("Binary search eliminates candidates from a known interval.","initial candidates","eliminated candidates","remaining candidates","subtract","binary-search interval invariant","items"),("A dynamic program fills equal numbers of states in repeated rows.","states per row","row count","table states","multiply","dynamic-program state decomposition","states"),("A graph traversal processes two disconnected components.","first component visits","second component visits","total visits","add","graph traversal visitation invariant","vertices"),("A sorting pass compares adjacent pairs across repeated passes.","comparisons per pass","pass count","total comparisons","multiply","comparison-sort cost model","comparisons")),
"COMPUTATIONAL_THINKING": (("A decomposition splits a task into two disjoint sets of subtasks.","first subtask count","second subtask count","total subtasks","add","problem decomposition","tasks"),("A pattern classifier compares matched cases with all cases.","matched cases","observed cases","match rate","percent","pattern-recognition rate","percent"),("A simulation repeats an equal number of steps for each trial.","steps per trial","trial count","executed steps","multiply","bounded simulation design","steps"),("A debugging trace removes confirmed-correct statements from all statements.","all traced statements","confirmed statements","suspect statements","subtract","fault-isolation procedure","statements"),("An abstraction combines two nonoverlapping state groups.","first abstract states","second abstract states","model states","add","state-space abstraction","states")),
"BIOLOGY": (("Replicate cultures yield two independently counted cell groups.","first culture cells","second culture cells","observed cells","add","controlled biological replication","cells"),("A cell's ATP ledger records production and consumption.","ATP produced","ATP consumed","net ATP","subtract","cellular energy conservation","ATP molecules"),("A genetic cross counts offspring with a phenotype among all offspring.","phenotype count","offspring count","phenotype frequency","percent","Mendelian phenotype frequency","percent"),("An ecosystem survey combines individuals from two nonoverlapping quadrats.","first quadrat count","second quadrat count","sample abundance","add","ecological sampling additivity","organisms"),("A population experiences equal additions across repeated generations.","addition per generation","generation count","population addition","multiply","population accounting","organisms")),
"ORGANIC_CHEMISTRY": (("Two resonance contributors assign electron counts to the same bounded atom set.","first electron contribution","second contribution","accounted electrons","add","valence-electron conservation","electrons"),("A proton-transfer experiment compares initial and remaining acid equivalents.","initial acid equivalents","remaining equivalents","transferred equivalents","subtract","Brønsted acid-base stoichiometry","mmol"),("A reaction vessel combines two portions of the same substrate.","first substrate amount","second substrate amount","total substrate","add","organic reaction mass accounting","mmol"),("A stereochemical sample counts one enantiomer among all molecules sampled.","selected enantiomer count","sample count","enantiomer percentage","percent","stereochemical composition","percent"),("Two spectroscopy integrations belong to nonoverlapping proton environments.","first integration","second integration","total integrated protons","add","NMR integration accounting","protons")),
"BIOCHEMISTRY": (("A pathway produces ATP in two substrate-level steps.","first-step ATP","second-step ATP","pathway ATP","add","metabolic energy accounting","mmol ATP"),("A buffer preparation combines conjugate-base portions.","first base amount","second base amount","total conjugate base","add","buffer component conservation","mmol"),("An enzyme assay divides converted substrate by elapsed time.","substrate converted","elapsed time","initial rate","ratio","enzyme rate definition","umol/min"),("A membrane experiment counts transported molecules among presented molecules.","transported molecules","presented molecules","transport percentage","percent","selective membrane transport","percent"),("A protein contains repeated residues in equal subunits.","residues per subunit","subunit count","protein residues","multiply","protein subunit stoichiometry","residues")),
}

COURSE_IDS = tuple(BLUEPRINTS)
_PHYSICS_ENGINES = ("numeric_scalar","numeric_scalar","numeric_scalar","numeric_vector","numeric_scalar")
_CS_ENGINES = ("code_execution","multiple_choice","numeric_vector","rubric_scored_explanation","code_execution")
_LIFE_ENGINES = ("scientific_structured_response","rubric_scored_explanation","numeric_scalar","multiple_choice","scientific_structured_response")


def _build() -> tuple[DomainRecipe, ...]:
    rows=[]
    for course, specs in BLUEPRINTS.items():
        engines = _CS_ENGINES if course in {"DATA_STRUCTURES","ALGORITHMS","COMPUTATIONAL_THINKING"} else (_LIFE_ENGINES if course in {"BIOLOGY","ORGANIC_CHEMISTRY","BIOCHEMISTRY"} else _PHYSICS_ENGINES)
        indexes = (1,2,3,4,7) if course in {"ORGANIC_CHEMISTRY","BIOCHEMISTRY"} else (1,2,3,4,5)
        for spec, engine, index in zip(specs, engines, indexes):
            context, first, second, result, operation, principle, unit = spec
            binding=RecipeBinding(course,f"{course}_TOPIC_{index:03d}",f"{course}_SKILL_{index:03d}",f"{course}_PROC_{index:03d}",f"{course}_FAMILY_{index:03d}",engine)
            rows.append(DomainRecipe(f"W056:{course}:{index:03d}","1.0.0",binding,(first,second,result),operation,principle,context,unit))
    return tuple(rows)


RECIPES = _build()


def recipes_for_course(course_id: str) -> tuple[DomainRecipe, ...]:
    if course_id not in COURSE_IDS: raise KeyError(f"no exact recipe binding for {course_id}")
    return tuple(r for r in RECIPES if r.binding.course_id == course_id)


def self_audit() -> dict[str, Any]:
    rows=[]; prompts=[]
    for course in COURSE_IDS:
        recipes=recipes_for_course(course); compiled=[r.compile(v) for r in recipes for v in range(5)]
        prompts.extend(x.prompt for x in compiled)
        rows.append({"course_id":course,"recipes":len(recipes),"questions":len(compiled),"families":len({r.binding.family_id for r in recipes}),"skills":len({r.binding.micro_skill_id for r in recipes}),"procedures":len({r.binding.procedure_id for r in recipes}),"engines":len({r.binding.engine_type for r in recipes}),"difficulties":len({x.difficulty for x in compiled}),"independent_derivations":sum(x.generated_answer==x.independently_derived_answer for x in compiled)})
    duplicate_count=sum(n-1 for n in Counter(prompts).values() if n>1)
    valid=all(r["recipes"]>=5 and r["questions"]==25 and r["families"]>=5 and r["skills"]>=5 and r["procedures"]>=3 and r["engines"]>=2 and r["difficulties"]>=2 and r["independent_derivations"]==25 for r in rows)
    return {"status":"PASS" if valid and not duplicate_count else "FAIL","course_count":len(rows),"recipe_count":len(RECIPES),"question_count":sum(r["questions"] for r in rows),"independent_derivations":sum(r["independent_derivations"] for r in rows),"exact_prompt_duplicates":duplicate_count,"rows":rows}
